# Build base image before building this image
FROM n622jwith/ml_base:latest

# Set shell option
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Switch to user
ARG USER_NAME
USER ${USER_NAME}
WORKDIR /home/${USER_NAME}

# Install python packages
# copy requirements.txt
COPY requirements.txt /home/${USER_NAME}/requirements.txt
# Install python packages
RUN /bin/bash -c "source /home/${USER_NAME}/.venv/bin/activate && pip3 install --no-cache-dir -r requirements.txt"

# Copy setup.sh and run
COPY setup.sh /home/${USER_NAME}/setup.sh
RUN bash ~/setup.sh

CMD ["/bin/bash"]
